version: '3.3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfiledb
    ports:
    - "5003:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "5001:80"
    restart: always
 # api:
  #  container_name: 'apitasks'
   # build: './apitasks'
    #ports:
     # - '8080:8080'
    #depends_on:
     #
     # - 'mongo'
 