FROM golang:1.15.6

LABEL maintainer = "Sergio Vera"
#Carpeta donde se alojara la app en el contenedor
RUN mkdir /app
#Añadimos todo el directorio raiz a la carpeta app de nuestro contenedor
ADD . /app
#Establecemos el directorio /app como directorio de trabajo
WORKDIR /app
RUN export GO111MODULE="on"
COPY go.mod go.sum ./
RUN ls
# Ejecutamos los test del codigo que existan
#RUN go test ./...
# Descargamos las dependencias e instalamos (creamos ejecutable) del programa
RUN go mod download 
COPY . .
RUN go build -o main
RUN ls
#RUN go get ./...
#RUN go run main.go

#Arrancamos nuestra aplicacion
CMD [ "/app/main" ]